services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./api
    container_name: fastapi_producer
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SENDER_EMAIL=${SENDER_EMAIL}
    depends_on:
      - rabbitmq
    restart: always
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit_server
    ports:
      - "1025:1025" 
      - "8025:8025"

