version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notifier_network

  api:
    build: ./api
    container_name: fastapi_producer
    ports:
      - "8000:8000"
    networks:
      - notifier_network
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    container_name: python_worker
    networks:
      - notifier_network
    depends_on:
      - rabbitmq
    restart: always

networks:
  notifier_network:
    driver: bridge